FROM php:8.1.16-fpm

#環境変数の設定
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer
# Viteのサーバーにローカルからアクセスするために開ける
EXPOSE 5173

# COPY php.ini
COPY ./docker/php/php.ini /usr/local/etc/php/php.ini

# Composer install
COPY --from=composer:2.5.4 /usr/bin/composer /usr/bin/composer

# install Node.js
COPY --from=node:18.14.2 /usr/local/bin /usr/local/bin
COPY --from=node:18.14.2 /usr/local/lib /usr/local/lib

RUN apt-get update \
  && apt-get install -y git zlib1g-dev libzip-dev zip unzip libpng-dev libjpeg-dev curl wget \
  && docker-php-ext-install zip pdo_mysql && \
  pecl install xdebug && \
    docker-php-ext-enable xdebug && \
  apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html
